<a href="https://colab.research.google.com/github/Mangoperu/Simple-Python/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!pip install scikit-learn --upgrade --quiet

In [10]:
!pip install opendatasets --upgrade --quiet

In [11]:
import numpy as np
import pandas as pd
import opendatasets as od

In [12]:
!pip install plotly matplotlib seaborn --quiet

In [13]:
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

In [14]:
dataset_url = 'https://www.kaggle.com/datasets/yasserh/titanic-dataset/data'
od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: Mangoaam
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/yasserh/titanic-dataset
Downloading titanic-dataset.zip to ./titanic-dataset

100%|██████████| 22.0k/22.0k [00:00<00:00, 3.92MB/s]

In [15]:
data_path = '/content/titanic-dataset/Titanic-Dataset.csv'

In [16]:
data = pd.read_csv(data_path)

In [17]:
data.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [19]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [20]:
data = pd.DataFrame(data.drop(["Cabin" , "PassengerId" , "Name","Ticket"] , axis = 1 ))

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [22]:
px.histogram(data , x = 'Survived' , color = 'Sex')

In [23]:
px.histogram( data[data["Survived"] == 1] , x = 'Pclass' , color = 'Sex')

In [24]:
px.histogram( data[data["Survived"] != 1] , x = 'Pclass' , color = 'Sex')

In [25]:
px.histogram( data , x = 'Fare' , color = 'Survived')

In [26]:
#data.dropna(subset=['Age'] , inplace = True )
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer.fit(data[['Age']])

SimpleImputer()

In [27]:
data['Age'] = imputer.transform(data[['Age']])

In [28]:
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [29]:
data['Sex'].replace(['male' , 'female'] , [1 , 0 ] , inplace=True)

/tmp/ipykernel_1765/3670675808.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_1765/3670675808.py:1: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [30]:
data

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    1  22.000000      1      0   7.2500        S
1           1       1    0  38.000000      1      0  71.2833        C
2           1       3    0  26.000000      0      0   7.9250        S
3           1       1    0  35.000000      1      0  53.1000        S
4           0       3    1  35.000000      0      0   8.0500        S
..        ...     ...  ...        ...    ...    ...      ...      ...
886         0       2    1  27.000000      0      0  13.0000        S
887         1       1    0  19.000000      0      0  30.0000        S
888         0       3    0  29.699118      1      2  23.4500        S
889         1       1    1  26.000000      0      0  30.0000        C
890         0       3    1  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [31]:
#dummies = pd.get_dummies(data['Embarked']  , dtype = int)
#dummies

In [32]:
#data = pd.concat([data , dummies] , axis = 1).drop(['Embarked'] , axis = 1)

In [33]:
input_cols = list(data.columns)[1:-1]
target = 'Survived'

In [34]:
print("input columns = " , input_cols)
print("target columns = " , target)

input columns =  ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
target columns =  Survived

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
encoder = OneHotEncoder(sparse_output = False , handle_unknown = 'ignore')

In [37]:

data['Embarked'] = data['Embarked'].fillna("unknown")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(5), object(1)
memory usage: 55.8+ KB

In [38]:
encoder.fit(data[['Embarked']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [39]:
encoder.categories_

[array(['C', 'Q', 'S', 'unknown'], dtype=object)]

In [40]:
encoded_cols = encoder.get_feature_names_out(list(['Embarked']))
print(encoded_cols)

['Embarked_C' 'Embarked_Q' 'Embarked_S' 'Embarked_unknown']

In [41]:
data[encoded_cols] = encoder.transform(data[['Embarked']])

In [42]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Embarked_C,Embarked_Q,Embarked_S,Embarked_unknown
0,0,3,1,22.0,1,0,7.2500,S,0.0,0.0,1.0,0.0
1,1,1,0,38.0,1,0,71.2833,C,1.0,0.0,0.0,0.0
2,1,3,0,26.0,0,0,7.9250,S,0.0,0.0,1.0,0.0
3,1,1,0,35.0,1,0,53.1000,S,0.0,0.0,1.0,0.0
4,0,3,1,35.0,0,0,8.0500,S,0.0,0.0,1.0,0.0

In [43]:
data = data.drop(['Embarked']  , axis  =1)

In [44]:
data.head()
all_cols = data.columns

In [45]:

from sklearn.preprocessing import MinMaxScaler

In [46]:
scaler = MinMaxScaler()

In [47]:
data = scaler.fit_transform(data)

In [48]:
data = pd.DataFrame(data  , columns = all_cols)

In [49]:
data.head()
input_cols = data.columns[1:-1]

In [50]:
data.describe()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Embarked_unknown
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,0.654321,0.647587,0.367921,0.065376,0.063599,0.062858,0.188552,0.086420,0.722783,0.002245
std,0.486592,0.418036,0.477990,0.163383,0.137843,0.134343,0.096995,0.391372,0.281141,0.447876,0.047351
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.500000,0.000000,0.271174,0.000000,0.000000,0.015440,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,1.000000,0.367921,0.000000,0.000000,0.028213,0.000000,0.000000,1.000000,0.000000
75%,1.000000,1.000000,1.000000,0.434531,0.125000,0.000000,0.060508,0.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
train_val, test_data = train_test_split(data , test_size=0.2  , random_state=42)
train_data , val_data = train_test_split(train_val , test_size=0.25  , random_state=42)

In [53]:
train_inputs = train_data[input_cols].copy()
train_targets = train_data[target].copy()

In [54]:
test_inputs = test_data[input_cols].copy()
test_targets = test_data[target].copy()

In [55]:
val_inputs = val_data[input_cols].copy()
val_targets = val_data[target].copy()

In [56]:
input_cols

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [57]:
!pip install pyarrow --quiet

In [58]:
train_inputs.to_parquet('train_inputs.parquet')
val_inputs.to_parquet('val_inputs.parquet')
test_inputs.to_parquet('test_inputs.parquet')

In [59]:
%%time
pd.DataFrame(train_targets).to_parquet('train_targets.parquet')
pd.DataFrame(val_targets).to_parquet('val_targets.parquet')
pd.DataFrame(test_targets).to_parquet('test_targets.parquet')

CPU times: user 7.29 ms, sys: 0 ns, total: 7.29 ms
Wall time: 8.43 ms

In [60]:
%%time

train_inputs = pd.read_parquet('train_inputs.parquet')
val_inputs = pd.read_parquet('val_inputs.parquet')
test_inputs = pd.read_parquet('test_inputs.parquet')

train_targets = pd.read_parquet('train_targets.parquet')[target]
val_targets = pd.read_parquet('val_targets.parquet')[target]
test_targets = pd.read_parquet('test_targets.parquet')[target]

CPU times: user 33.3 ms, sys: 6.14 ms, total: 39.4 ms
Wall time: 70 ms

In [61]:
print('train_inputs:', train_inputs.shape)
print('train_targets:', train_targets.shape)
print('val_inputs:', val_inputs.shape)
print('val_targets:', val_targets.shape)
print('test_inputs:', test_inputs.shape)
print('test_targets:', test_targets.shape)

train_inputs: (534, 9)
train_targets: (534,)
val_inputs: (178, 9)
val_targets: (178,)
test_inputs: (179, 9)
test_targets: (179,)

**Traning**

In [62]:
from sklearn.linear_model import LogisticRegression

In [63]:
model = LogisticRegression(solver='liblinear')

In [66]:
model.fit(train_inputs[input_cols], train_targets)

LogisticRegression(solver='liblinear')

In [67]:
print(model.coef_.tolist())

[[-1.7113111448482616, -2.3703361857017677, -0.9785224277153108, -0.9712156719725968, -0.3993870353389135, 0.7404390818197939, 0.8390319446397084, 0.621422574655914, 0.24769716240924902]]

In [68]:
X_train = train_inputs[input_cols]
X_val = val_inputs[input_cols]
X_test = test_inputs[input_cols]

In [72]:
test_pred = model.predict(X_test)

In [73]:
test_pred

array([0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1.])

In [74]:
from sklearn.metrics import accuracy_score

In [75]:
accuracy_score(test_targets, test_pred)

0.8044692737430168

In [76]:
valid = LogisticRegression(solver='liblinear')

In [77]:
val_pred = model.predict(X_val)

In [79]:
accuracy_score(val_pred , val_targets)

0.797752808988764

In [80]:
train_pred = model.predict(X_train)

In [81]:
accuracy_score(train_pred  , train_targets)

0.7940074906367042

In [83]:
from sklearn.metrics import confusion_matrix

In [85]:
confusion_matrix(train_targets, train_pred, normalize='true')

array([[0.86445783, 0.13554217],
       [0.32178218, 0.67821782]])

In [86]:
import joblib

In [91]:
titanic_life_predictor = {
    'model': model,
    'imputer': imputer,
    'scaler': scaler,
    'encoder': encoder,
    'input_cols': input_cols,
    'target_col': target,
    'encoded_cols': encoded_cols
}

In [92]:
joblib.dump(titanic_life_predictor , 'titanic_life_predictor.joblib')

['titanic_life_predictor.joblib']

In [93]:
tit = joblib.load('titanic_life_predictor.joblib')